# frozen_string_literal: true

source "https://rubygems.org"

gem 'cosmos-llm', path: '../cosmos-llm-ruby-client'
gem 'cosmos-llm-tool', path: '../cosmos-llm-ruby-tool'
gem 'cosmos-llm-virtual-filesystem', path: '../cosmos-llm-ruby-virtual-filesystem'

gemspec

gem 'rake', '~> 13.0'

gem 'minitest', '~> 5.0'

gem 'rubocop', '~> 1.21'
