# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in cosmos-llm-tool.gemspec
gemspec

gem 'rake', '~> 13.0'

gem 'minitest', '~> 5.0'

gem 'rubocop', '~> 1.21'

# For local development
gem 'cosmos-llm', path: '../cosmos-llm-ruby-client'
