# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in cosmos-llm-virtual-filesystem.gemspec
gemspec

gem 'rake', '~> 13.0'

gem 'minitest', '~> 5.0'

gem 'rubocop', '~> 1.0', require: false
